import { Inter } from "next/font/google";
import "./globals.css";
import { useLocale } from "next-intl";
import { notFound } from "next/navigation";
import { defaultLocale } from "@/config/locales";

// components
import NavBar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  const locale = useLocale();
  console.log("locale", locale);

  if (params.locale !== locale) {
    notFound();
  }

  return (
    <html lang={defaultLocale || locale}>
      <body className={inter.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
